// poemData.js

const poemData = [
    {
      title: "My Child brings no trophies home",
      content: "My child brings no trophies home.\nHe brings no laurels or accolades home.\nHe brings no success stories to boost my pride.\nWhat he does, is he brings in failure after failure.\nI cry and I try again.\nBut he and I fail again.\nWe both live in the fantasy world of our unfulfilled dreams.\nMy child makes no history but he sure is a mystery.\nBut why do I judge?\nAm I not a mystery too?\nMy child does not hit the headlines.\nBut when he does, it is to re-establish that he is a failure yet again.\nBut my child was no criminal in my womb.\nBut why Lord didn't him or I bring trophies home?\nThe frothy frolic of the bath tub of his childhood\nHas today turned into smears of blood strain on my breast.\nWhen I lay in death, my child is not there by my side to put me to rest.\nBut he does not cease to be my child nor me his mom.\nThen what went wrong?\nIf I can solve this mystery, then all children will bring trophies home.\nBut Lord, if we cannot then do take us home to you cause no matter what, You don't cease to love us just because we don't bring trophies home.\n"
    },
    {
      title: "DON'T BLAME MY BROTHER FOR A CRIME HE COMMITTED NEVER",
      content: "Don't blame my brother for a crime he committed never.\nYes, he was the villain of the Masterpiece.\nHe roared like a lion,\nHe kicked like a horse,\nHe threw things like a javelin thrower.\nHe broke promises,\nHe broke hearts,\nHe broke bones,\nHe broke homes,\nHe marred prestige.\nHe did it all.......\nAnd you were the Sweet Angel to the World.\nYou covered and you nurtured.\nYou kept everything going.\nYou were the Angel to the World.\nBut within the confines of the walls\nYou attacked most fatally.\nYou did not roar like a lion nor kicked like a horse.\nBut you struck in the stealthy silence of a reptile.\nYou sucked all his jest away......\nOn the Anniversary of your birth,\nHe stood outside the jewelers shop\nTo get you your desired piece.\nBut when the constraints of his pocket failed him.\nHe drank to drown his pain.\nAnd instead of wishing you, he abused you.\nIn the eye of the world, he abused you.\nBut in the truth of the circumstance, he abused himself in the bitterest of terms.\nDon't blame my brother for a crime he committed never.\nHe staggered around in the filth of his tatters and stinking breathe.\nBut you walked steadily in the garb of righteousness.\nYou were the Angel to the World\nAnd He the villain of the Masterpiece.......\nSometimes when there was an uproar in public,\nIt was him, trying to fight for you.\nTo fight your battle.......\nBut you in turn humiliated him because in the staggering of his footsteps he lost the argument even before it began.\nDon't blame my brother for a crime he committed never.\nIn his own special way, he stood by you forever.\nBut you never ceased an opportunity to humiliate him.\nYou did everything for him......\nSo how could you not be the Angel to the World and He the Villain of the Masterpiece?\nYou gave him everything yet he abused you.\nHe gave you his soul....\nHe gave you his name....\nHe gave you his protection in his own special way.\nThe World said, He took away everything of yours.\nHe ruined your life\nSaid your friends.\nHe broke your home they said and so did you.\nBut, You Angel of the World broke his very spirit.......\nYou took away his very identity.\nAnd you say, He is the villain of the Masterpiece?\nDon't ever blame my brother for a crime he committed never.\n"
    },
    {
      title: "Creations",
      content: "Have you ever seen the receeding horizon?\nWhen the sun kisses the sky goodbye with its magnificient Orange?\nHave you ever experienced the silent beauty of the dusk descending on Earth?\nHave you ever watched the birds flying off to the restful nest of the night?\nHave you ever felt the cold breeze of the night slowly griping the trees?\nHave you ever seen the trees standing right there whether night or day?\nHave you ever been there when the herds go in a beeline to their shelter of the night?\nIt is at this hour of transition that I sit in quiet repose\nTo pen down all the transmissions received by the canvas of my mind\nIn the years gone by.\nI, no lover of nature, but of humans\nI, who never appreciated these, sit today in quiet repose\nAnd wonder?\nWas I really blind as I appeared?\nNo my friends, I was not.\nI was only silently absorbing it all in the din of life.\nIt took me forty four years to soak it all.\nAnd today I ask you\nHave you ever sniffed the rain?\nHave you ever felt the presence of the oncoming storm?\nHave you heard the breeze whispering to you?\nHave you ever felt the presence of the Infinite?\nI have in its creations today.\nHave you ever seen the radiance of the embers of a fire place?\nHave you ever felt the icy cold of the running water of a mountain brook?\nCan you ever describe the rainbow?\nCan you ever compare the beauty of a night sky?\nCan you ever create the change of color of the seasons?\nCan you ever touch the horizon?\nNo, you cannot.\nYou only see, feel and let it pass\nTo your inner soul for it to come out\nIn the quiet repose of the descending night.\n"
    },
    {
      title: "I AM RIGHT HERE",
      content: "Don't search for me atop a mountain range.\nDon't search for me in the depth of the jungles.\nDon't search for me in the core of a cave.\nSearch for me in your heart.\nI am right there.\nDon't search for me in the knowledge of the volumes.\nDon't search for me in the grandiosity of a Cathedral.\nDon't search for me in the din of the temple.\nSearch for me in the goodness of your deeds.\nI am right there.\nDon't search for me in the business of the linkman.\nDon't search for me in the loudspeaker of a mosque.\nDon't search for me in the rigidity of the rituals.\nSearch for me in your heart.\nAnd I am right there in your inner voice.\nDon't search for me in the silence of the Monastery.\nDon't search for me in the chanting of the Temple.\nDon't search for me with rigorous penance.\nSearch for me in the innocence of a child.\nI am right there.\nDon't search for me in the queue of The Slaughter House.\nDon't search for me in the bribe of the blood.\nDon't search for me in the Gold of the Dome.\nSearch for me in the hut of the Devotee.\nI am right there.\nDon't search for me in the silken robes of the priest.\nDon't search for me in the Wine of the Goblet.\nDon't search for me in the maddening rush of the masses to reach me first.\nSearch for me in the limp of the physically challenged\nI am right there.\nDon't search for me only among humans.\nDon't search for me in the beauty of the flower.\nDon't search for me in the depth of the sea.\nSearch for me in the wound of a stoned stray dog.\nI am right there.\nDon't search for me in the loads of the Donation Box.\nDon't search for me only among the lettered.\nDon't search for me in the solemn celebrations.\nSearch for me in the simplicity of the peasant.\nI am right there.\nDon't search for me in the dogma of religion.\nAnd be so lost that you miss me totally because\nI am right there\nIn the heart of all my children.\n"
    },
    {
      title: "THE VOICE OF THE COUNSELLEE",
      content: "Don't bombard me with volley of bullets from your degrees.\nDon't counsel me from the Ivory Tower of your knowledge.\nDon't walk past me in my home, as you would in a zoo pass.\nDon't make me and my life a case study for your academic interest and bare me of my pain.\nIf you really want to help me, be there with me.\nDon't elate with joy because you have learnt about me.\nBe silent in your acceptance of understanding me.\nDon't look at me from the point of view of strength.\nStand next to me and be equal in my pain.\nBe that unassuming man who guided me through my blindness but never set to make an impact in the so called 'intellectual circles'.\nBe that nanny who wiped away my tears and washed my knickers for a living, true, but a living which slowly became a way of life most close to her heart.\nBe that person, who gave it all up because she wanted that you should have it all.\nBe that man who chose to feel your pain much more than ever you realized you did.\nDon't hide there in the garb of a counsellor and terminate' your session because you never understood me nor felt my pain.\nDon't decorate the word \"empathy' and touch me just because it is required. You have to first touch my heart if you really want to help me.\nDon't pretend to empathize with me because you need an earning through\nme.\nI have enough pain; spare me of your inner indifference.\nOr else how could you pretend to 'understand me' through a power point presentation?\nDid a mother ever learn to love her child?\nOr did a mother ever 'retire' from her post?\nDid your mother do that to you?\nYou need an earning, true, so go ahead with it but don't make me and my pain a guinea pig in your brainstorming\nTry if you can, to heart storm my pain.\nDon't just visit me on a bright autumn morning and forget about me for the rest of your life.\nDon't stand there in your hierarchy and send emissaries to me but cease to be there in person.\nDon't forget I am a human being just like you.\nDon't send people to me just to prove how much you know about my world I don't want those people, I want you.\nDon't close your door on me because the clock has struck time out\nDon't say you have 'burn out just because you have heard me out for a brief while........\nI wonder what the world would have been like if God said He needed time out' for 'burn out.\nIf you really want to help me, be there with me in spirit.\nBe one with me.\nDon't use jargons; if possible don't pain me further with your endless discussions on me.\nDon't learn about me just because you need to write a report on my world. Don't learn about me just because you want to add pages to your thesis. Don't learn about me only because you want statistics.\nIf you really want to help me, be there with me.\nBe a Real Part of my World."
    }
  ];
  
  export default poemData;
  